name: Deploy

on:
  push:
    branches: [main]

jobs:
  cd:
    name: Deploy prod
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: SSH and update server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/ui
            git pull
            cd /var/www
            docker compose up -d --build
            docker image prune -f
